### ISSUE TITLE
Can not figure out how to login with correct password.

### ISSUE THREAD

**Issue by sulisu** [lennart-k/rustical#7]
Hello, I started rustical with docker-compose.yml

```
services:
  rustical:
    image: ghcr.io/lennart-k/rustical:main
    container_name: rustical
    ports:
      - "4000:4000"
    volumes:
      - ${PWD}/rustical/config.toml:/etc/rustical/config.toml

```

Then, I created password hash with following commands and put them in config
docker exec -it rustical  /usr/local/bin/rustical pwhash --algorithm argon2
docker exec -it rustical  /usr/local/bin/rustical pwhash --algorithm pbkdf2

password is 123456

config.toml

```
[data_store]
backend = "sqlite"
db_url = ""

[auth]
backend = "static"

[[auth.users]]
id = "default"
displayname = "Default user"
password = "$argon2id$v=19$m=19456,t=2,p=1$KDiKMiJJ3RnZUojM49wx3w$wCnSBm9glJL2xxna++2pW5wDTAS0WPQ8AGkAllj85Co"
app_tokens = ["$pbkdf2-sha256$i=1000,l=32$RGDaZ3tILIRGMmuBhLoUMA$oXCNM6UcrcxYOLWt/TK4utYaH1fWFsjm6JBYTyTb7yM"]

[http]
host = "0.0.0.0"
port = 4000

[frontend]
secret_key = "e773b8322ebf0d3495183fce33761bf76dee224e978a47d89c58679b81b6a24fae35081a8ecef78d3820dd09939af82816ae6aea3e66579cfaf4c8247f35aca5"

[tracing]
opentelemetry = false

```

But I cannot login web frontend with default:123456, it always return unauthorized. And what the usage of frontend secret_key?
