### ISSUE TITLE
Problems with Nextcloud flow

### ISSUE THREAD

**Issue by poperigby** [lennart-k/rustical#89]
I've setup Rustical in the following way:

`config.toml`:
```toml
[data_store.sqlite]
db_url = "/var/lib/rustical/db.sqlite3"

[dav_push]
enabled = true

[frontend]
allow_password_login = false
enabled = true

[http]
host = "0.0.0.0"
port = 4000

[nextcloud_login]
enabled = true

[oidc]
allow_sign_up = true
claim_userid = "preferred_username"
issuer = "https://auth.haddock.cc"
name = "Authelia"
scopes = ["openid", "profile", "groups"]

[tracing]
opentelemetry = false
```

Authelia OIDC client configuration:

```yaml
- client_name: "Rustical"
  client_id: {{ secret "/run/secrets/rustical-oidc-client-id_authelia" | mindent 10 "|" | msquote }}
  client_secret: {{ secret "/run/secrets/haddock/rustical/oidc_client_secret/authelia" | mindent 10 "|" | msquote }}
  public: false
  authorization_policy: "one_factor"
  consent_mode: "implicit"
  scopes: ["openid", "profile", "groups"]
  token_endpoint_auth_method: "client_secret_basic"
  redirect_uris:
    - "https://dav.haddock.cc/frontend/login/oidc/callback"
```

When I try to login via the Nextcloud flow in DAVx5, I get the following error:

```
at.bitfire.dav4jvm.exception.HttpException: HTTP 401
```

I also receive this in my Authelia log:

```json
{
  "level": "info",
  "method": "GET",
  "msg": "Access to https://dav.haddock.cc/index.php/login/v2 (method POST) is not authorized to user \\u003canonymous\\u003e, responding with status code 401 with location redirect to https://auth.haddock.cc/?rd=https%3A%2F%2Fdav.haddock.cc%2Findex.php%2Flogin%2Fv2\\u0026rm=POST",
  "path": "/api/authz/forward-auth",
  "remote_ip": "192.168.1.1",
  "time": "2025-06-28T13:58:50-07:00"
}
```

I'm using Rustical v0.4.6
